#!/usr/bin/env python3
"""
trace_runtime.py — Level 2 dynamic runtime file-access tracer for lang-migration P1.

Observes which files the source project ACTUALLY opens while running its test
suite, then diffs that set against asset-inventory.yaml. This catches runtime
dependencies that static analysis cannot see (variable paths, config-driven
paths, framework plugin loaders).

Usage:
    # Python project (audit-hook mode, no external tools needed):
    python3 trace_runtime.py --source <source_dir> \
        --inventory migration_workspace/asset-inventory.yaml \
        --output migration_workspace/runtime-access-trace.yaml \
        -- python -m pytest

    # Any language on Linux (strace mode):
    python3 trace_runtime.py --source <source_dir> \
        --inventory migration_workspace/asset-inventory.yaml \
        --output migration_workspace/runtime-access-trace.yaml \
        --mode strace -- go test ./...

Modes:
    audit   Inject a sitecustomize.py with sys.addaudithook into PYTHONPATH.
            Works for any Python entrypoint (pytest, python -m, scripts) and
            child Python processes. Zero external dependencies.
    strace  Run the command under `strace -f -e trace=open,openat`. Works for
            any language; requires strace (Linux only).
    auto    (default) audit if the command starts with python/pytest, else
            strace if available, else error.

Exit codes:
    0  trace completed, no findings (all accessed files properly classified)
    1  trace completed, findings exist (see output YAML)
    2  usage or environment error (command failed to start, strace missing, ...)
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip install pyyaml --break-system-packages")
    sys.exit(2)

# Reuse the skip list from scan_assets.py so both tools agree on noise dirs
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    from scan_assets import SKIP_PATTERNS
except ImportError:
    SKIP_PATTERNS = {
        ".git", ".svn", "__pycache__", ".pytest_cache", ".mypy_cache",
        "node_modules", ".venv", "venv", "env", ".env",
        "dist", "build", "target", "_build", ".build",
        ".DS_Store", "Thumbs.db", "migration_workspace",
    }

SITECUSTOMIZE_SRC = '''\
# Auto-generated by trace_runtime.py — installs a file-open audit hook.
import os as _os
import sys as _sys

_log_path = _os.environ.get("LANG_MIG_TRACE_LOG")
if _log_path:
    try:
        _log = open(_log_path, "a", buffering=1, encoding="utf-8")

        def _lang_mig_hook(event, args):
            if event == "open":
                try:
                    p = args[0]
                    if isinstance(p, bytes):
                        p = p.decode("utf-8", "replace")
                    if isinstance(p, str):
                        _log.write(p + "\\n")
                except Exception:
                    pass

        _sys.addaudithook(_lang_mig_hook)
    except Exception:
        pass
'''

# strace line: openat(AT_FDCWD, "/path/to/file", O_RDONLY) = 3
# We keep only successful opens (return value >= 0); failed probes (ENOENT) are noise.
STRACE_OPEN_RE = re.compile(
    r'\bopen(?:at|at2)?\((?:[^,]+,\s*)?"([^"]+)"[^)]*\)\s*=\s*(\d+)'
)


def run_audit_mode(command, log_path: str) -> int:
    """Run command with a sitecustomize audit hook injected via PYTHONPATH."""
    with tempfile.TemporaryDirectory(prefix="lang_mig_trace_") as tmp:
        (Path(tmp) / "sitecustomize.py").write_text(SITECUSTOMIZE_SRC, encoding="utf-8")
        env = os.environ.copy()
        env["LANG_MIG_TRACE_LOG"] = log_path
        existing = env.get("PYTHONPATH", "")
        env["PYTHONPATH"] = tmp + (os.pathsep + existing if existing else "")
        result = subprocess.run(command, env=env)
        return result.returncode


def run_strace_mode(command, log_path: str) -> int:
    """Run command under strace, logging open/openat syscalls."""
    if not shutil.which("strace"):
        print("ERROR: strace not found. Install it or use --mode audit for Python projects.")
        sys.exit(2)
    strace_cmd = [
        "strace", "-f", "-qq",
        "-e", "trace=open,openat,openat2",
        "-o", log_path,
    ] + list(command)
    result = subprocess.run(strace_cmd)
    return result.returncode


def parse_audit_log(log_path: str) -> set:
    paths = set()
    with open(log_path, encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if line:
                paths.add(line)
    return paths


def parse_strace_log(log_path: str) -> set:
    paths = set()
    with open(log_path, encoding="utf-8", errors="replace") as f:
        for line in f:
            m = STRACE_OPEN_RE.search(line)
            if m:
                paths.add(m.group(1))
    return paths


def filter_source_paths(raw_paths: set, source_dir: str) -> list:
    """Keep only files under source_dir; return sorted relative paths.

    Excludes paths inside SKIP_PATTERNS directories (caches, venvs, etc.).
    """
    source = Path(source_dir).resolve()
    rel_paths = set()
    for raw in raw_paths:
        try:
            p = Path(raw)
            if not p.is_absolute():
                p = Path.cwd() / p
            p = p.resolve()
        except (OSError, ValueError):
            continue
        try:
            rel = p.relative_to(source)
        except ValueError:
            continue
        parts = rel.parts
        if any(part in SKIP_PATTERNS for part in parts):
            continue
        # Only files (a dir open via opendir also shows up in strace)
        if (source / rel).is_file():
            rel_paths.add(str(rel))
    return sorted(rel_paths)


def diff_against_inventory(accessed: list, inventory_path: str):
    """Compare accessed files against asset-inventory.yaml entries.

    Returns (findings, suggestions):
      findings    — accessed files missing from inventory, or classified
                    reference_only (= excluded from target despite runtime use)
      suggestions — accessed files correctly migrated but not yet tagged
                    runtime_dependency: true (informational)
    """
    with open(inventory_path, encoding="utf-8") as f:
        inventory = yaml.safe_load(f) or {}
    entries = {a["path"]: a for a in inventory.get("assets", [])}

    findings = []
    suggestions = []
    for rel in accessed:
        entry = entries.get(rel)
        if entry is None:
            findings.append({
                "path": rel,
                "kind": "missing_from_inventory",
                "detail": "file was opened at runtime but has no asset-inventory.yaml entry",
            })
            continue
        strategy = entry.get("migration_strategy", "")
        if strategy == "reference_only":
            findings.append({
                "path": rel,
                "kind": "runtime_use_of_reference_only",
                "detail": (
                    "file was opened at runtime but strategy is reference_only "
                    "(excluded from target project) — upgrade to direct_use or adapt"
                ),
            })
        elif not entry.get("runtime_dependency"):
            suggestions.append({
                "path": rel,
                "detail": (
                    f"opened at runtime (strategy: {strategy or 'unset'}); "
                    "consider tagging runtime_dependency: true for traceability"
                ),
            })
    return findings, suggestions


def main():
    parser = argparse.ArgumentParser(
        description="Trace runtime file access of the source project's test suite",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__.split("Usage:")[1] if "Usage:" in __doc__ else "",
    )
    parser.add_argument("--source", required=True, help="Path to source project root")
    parser.add_argument("--inventory", required=True, help="Path to asset-inventory.yaml")
    parser.add_argument("--output", required=True, help="Path to write runtime-access-trace.yaml")
    parser.add_argument("--mode", choices=["auto", "audit", "strace"], default="auto")
    parser.add_argument("command", nargs="+", help="Test command to run (after --)")
    args = parser.parse_args()

    if not os.path.isdir(args.source):
        print(f"Error: source dir not found: {args.source}")
        sys.exit(2)
    if not os.path.isfile(args.inventory):
        print(f"Error: inventory not found: {args.inventory} (run scan_assets.py first)")
        sys.exit(2)

    mode = args.mode
    if mode == "auto":
        head = os.path.basename(args.command[0])
        if head.startswith("python") or head in ("pytest", "py.test", "tox", "nox"):
            mode = "audit"
        elif shutil.which("strace"):
            mode = "strace"
        else:
            print("Error: cannot auto-select mode — command is not Python and strace is missing.")
            print("Use --mode audit (Python projects) or install strace.")
            sys.exit(2)

    log_fd, log_path = tempfile.mkstemp(prefix="lang_mig_trace_", suffix=".log")
    os.close(log_fd)
    try:
        print(f"Tracing ({mode} mode): {' '.join(args.command)}")
        if mode == "audit":
            rc = run_audit_mode(args.command, log_path)
            raw_paths = parse_audit_log(log_path)
        else:
            rc = run_strace_mode(args.command, log_path)
            raw_paths = parse_strace_log(log_path)
    finally:
        cleanup_log = log_path

    print(f"Test command exited with code {rc}; {len(raw_paths)} raw open events captured.")
    if not raw_paths:
        print("WARNING: zero file opens captured — the hook may not have engaged.")
        print("Audit mode requires the command to be a Python entrypoint; otherwise use --mode strace.")

    accessed = filter_source_paths(raw_paths, args.source)
    findings, suggestions = diff_against_inventory(accessed, args.inventory)

    trace = {
        "meta": {
            "generated_at": datetime.now().isoformat(),
            "mode": mode,
            "command": " ".join(args.command),
            "command_exit_code": rc,
            "source_dir": str(Path(args.source).resolve()),
            "raw_open_events": len(raw_paths),
            "source_files_accessed": len(accessed),
            "findings_count": len(findings),
            "note": (
                "Machine truth: every file listed under 'accessed' was actually opened "
                "by the source project at runtime. Derived artifact — regenerable; never hand-edit. "
                "Coverage caveat: only code paths exercised by the test command are observed."
            ),
        },
        "accessed": accessed,
        "findings": findings,
        "suggestions": suggestions,
    }

    out_dir = os.path.dirname(os.path.abspath(args.output))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        yaml.dump(trace, f, allow_unicode=True, default_flow_style=False, sort_keys=False)
    os.unlink(cleanup_log)

    print(f"\n{len(accessed)} source files accessed at runtime → {args.output}")
    if findings:
        print(f"\n⚠  {len(findings)} FINDING(S) — inventory does not match observed runtime behavior:")
        for fdg in findings:
            print(f"   [{fdg['kind']}] {fdg['path']}")
        print("\nFix each finding in asset-inventory.yaml, then re-run this trace.")
        sys.exit(1)
    if suggestions:
        print(f"\nℹ  {len(suggestions)} file(s) accessed at runtime but not tagged runtime_dependency: true (informational).")
    print("No findings — inventory is consistent with observed runtime file access.")
    sys.exit(0)


if __name__ == "__main__":
    main()
